name = "Basson AI"
license = "MIT"
licenselink = "https://github.com/tannerbyers/marketing-site-for-ai-email-template-generator/blog/main/LICENSE"
description = "The marketing site for AI Email Template Generator Micro-SaaS. We'll use this for wait list and blogging once MVP is deployed."
homepage = "https://github.com/zeon-studio/hugoplate"
demosite = "https://zeon.studio/preview?project=hugoplate"
min_version = "0.134.3"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "Tanner Byers"
homepage = "https://tannerbyers.com"

[original]
author = "Zeon Studio"
homepage = "https://zeon.studio"
repo = "https://github.com/zeon-studio/themeplate"
